### ISSUE TITLE
Getting a block element's modifier is not working correctly.

### ISSUE THREAD

**Issue by Leviatus21** [ZeeCoder/clam#4]
Getting a modifier with an expected "true/false" value fails, and simply returns an empty string.

Example:

```js
// .b-block__element--show
new modifier($hook, 'block__element');
ret = mod.get('show'); // Here the ret variable is "" instead of true. 
```

**Comment by ZeeCoder** [comment]
The "modifier" module is expected to be rewritten fully. Until then, no bugfixes are expected.
